### ISSUE TITLE
g.V("anything") and g.E("anything") do not work

### ISSUE THREAD

**Issue by clayu** [OyvindSabo/gremlint#39]
The formatter does not add spaces when the g.V or g.E contain arguments. 
There appears to be logic which is searching for exact matches to 'g.V()' and 'g.E()'

**Comment by OyvindSabo** [comment]
Hi, thanks for testing out Gremlint:grinning: I released a major rewrite yesterday. The previous version was mostly created as a prototype, with just one huge function with a bit of hard coding and a lot of parenthesis counters:see_no_evil:. The new version parses the query to a syntax tree, adds formatting information and then reprints it from scratch. Some minor things like comment support, syntax highlighting and being able to format multiple code blocks still remains to be implemented, but the issue you're pointing out should be fixed now.

Please [give it a try](https://gremlint.com/) and let me know what you think!
