### ISSUE TITLE
Add whitespace after comma

### ISSUE THREAD

**Issue by OyvindSabo** [OyvindSabo/gremlint#7]

**Comment by TheVaffel** [comment]
This was fixed with [fbc4](https://github.com/OyvindSabo/gremlint/commit/fbc466a763a44c11526a37da0ff4af4fb186f5db). **Your move.**

**Comment by OyvindSabo** [comment]
![1e43eb6a-da60-4cfc-a662-001d872f39af](https://user-images.githubusercontent.com/25663729/50366184-88bfdb00-0578-11e9-849f-27e35f34d454.jpeg)
